import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Explicit, not autogenerated: `unlisted: true` on docs/intro.mdx (the
  // internal theme-QA page) does NOT drop it from an autogenerated sidebar
  // tree — only from generated-index card grids and search. Listing the
  // real topic docs here is what actually keeps the QA page off-sidebar.
  docsSidebar: [
    'getting-started',
    'projects-quotes',
    'warehouse-fulfillment',
    'crew',
    'assets-kits',
  ],
};

export default sidebars;
