import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Auto-generated from the docs/ folder structure. The information
  // architecture for v1 content (Getting started, core concepts, per-module
  // guides — see gearflow issue #959) is deliberately not built out yet;
  // this bootstrap only proves the theme.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
