import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Explicit, not autogenerated: `unlisted: true` on docs/intro.mdx (the
 * internal theme-QA page) does NOT drop it from an autogenerated sidebar
 * tree — only from generated-index card grids and search. Listing the
 * real guide tree here is what actually keeps the QA page off-sidebar,
 * and it doubles as the one place that controls section order.
 *
 * Structure (docs-structure planning session, tracked in gearflow#959):
 * top level = business-function sections ordered as a user journey; each
 * section = an overview/concept page (the category link) plus verb-first
 * task pages. Getting Started and The Rental Workflow are the two guided
 * artifacts; everything after them is flat, searchable reference.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting started',
      link: {type: 'doc', id: 'getting-started/index'},
      items: [
        'getting-started/create-your-organization',
        'getting-started/set-up-your-catalogue',
        'getting-started/invite-your-team',
        'getting-started/your-first-project',
        'getting-started/quick-tour',
      ],
    },
    {
      type: 'category',
      label: 'The rental workflow',
      link: {type: 'doc', id: 'rental-workflow/index'},
      items: [
        'rental-workflow/enquiry-to-project',
        'rental-workflow/quote-to-confirmation',
        'rental-workflow/prep-and-dispatch',
        'rental-workflow/returns-and-close-out',
        'rental-workflow/invoicing-and-wrap-up',
      ],
    },
    {
      type: 'category',
      label: 'Projects',
      link: {type: 'doc', id: 'projects/index'},
      items: [
        'projects/create-a-project',
        'projects/add-equipment',
        'projects/sub-hires',
        'projects/sale-items',
        'projects/project-templates',
        'projects/project-tasks',
        'projects/availability-and-overbookings',
        'projects/versions-and-unlocking',
      ],
    },
    {
      type: 'category',
      label: 'Quotes & invoicing',
      link: {type: 'doc', id: 'quotes-invoicing/index'},
      items: [
        'quotes-invoicing/create-and-send-a-quote',
        'quotes-invoicing/discounts',
        'quotes-invoicing/invoices',
        'quotes-invoicing/payment-profiles-and-deposits',
      ],
    },
    {
      type: 'category',
      label: 'Assets & inventory',
      link: {type: 'doc', id: 'assets-inventory/index'},
      items: [
        'assets-inventory/add-your-gear',
        'assets-inventory/categories',
        'assets-inventory/kits',
        'assets-inventory/accessories',
        'assets-inventory/fleet-roi',
      ],
    },
    {
      type: 'category',
      label: 'Warehouse',
      link: {type: 'doc', id: 'warehouse/index'},
      items: [
        'warehouse/prep-and-picking',
        'warehouse/scanning-and-barcodes',
        'warehouse/deploying-gear',
        'warehouse/returns',
        'warehouse/check-items',
        'warehouse/shortages-and-conflicts',
        'warehouse/warehouse-documents',
      ],
    },
    {
      type: 'category',
      label: 'Crew',
      link: {type: 'doc', id: 'crew/index'},
      items: ['crew/assign-crew', 'crew/planner', 'crew/timesheets'],
    },
    {
      type: 'category',
      label: 'Clients & suppliers',
      link: {type: 'doc', id: 'clients-suppliers/index'},
      items: [
        'clients-suppliers/clients-and-contacts',
        'clients-suppliers/suppliers-and-purchase-orders',
      ],
    },
    {
      type: 'category',
      label: 'Maintenance & compliance',
      link: {type: 'doc', id: 'maintenance-compliance/index'},
      items: [
        'maintenance-compliance/maintenance-records',
        'maintenance-compliance/preventative-maintenance',
        'maintenance-compliance/report-an-issue',
        'maintenance-compliance/test-and-tag',
      ],
    },
    {
      type: 'category',
      label: 'Settings & administration',
      link: {type: 'doc', id: 'settings-administration/index'},
      items: [
        'settings-administration/members-roles-permissions',
        'settings-administration/project-numbering',
        'settings-administration/custom-fields',
        'settings-administration/sso',
      ],
    },
    {
      type: 'category',
      label: 'Integrations & AI',
      link: {type: 'doc', id: 'integrations/index'},
      items: [
        'integrations/xero',
        'integrations/woocommerce',
        'integrations/api-keys-and-ai-agents',
        'integrations/webhooks',
        'integrations/mira',
      ],
    },
    'troubleshooting/index',
    'glossary',
  ],
};

export default sidebars;
